installer/core/config/routes.rb
Rails.application.routes.draw do
  localized do
    get '/index', to: 'app/front#index', as: :app_index
  end

  # root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  post '/filter', to: 'admin/users#filter_by_role', as: :filter_by_role

  namespace :admin do
    root to: 'admin#root'

    namespace :rockets do
      get '/', action: :rockets
      post 'create/:rocket', action: :create, as: :create
      post 'install', action: :install
      post 'build/:rocket', action: :build, as: :build
      delete 'uninstall/:rocket', action: :uninstall, as: :uninstall
    end

    get '/seo/sitemap', to: 'seos#sitemap'
    get '/seo/robots', to: 'seos#robots'
    post '/seo/editor/save', to: 'seos#editor_save'

    resources :seos do
      post '/sort', action: :sort, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :roles do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get '/download', action: 'download', as: :download
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      # post '/show_description/:module/:action_name', action: 'show_description', as: :show_description
      # get(
      #   '/add_permissions',
      #   action: 'add_permissions',
      #   as: :add_permissions
      # )
      # post(
      #   '/create_permissions',
      #   action: 'create_permissions',
      #   as: :create_permissions
      # )
    end

    scope :roles do
      post(
        ':role_id/show_description/:module/:action_name',
        to: 'permissions#show',
        as: :role_show_description
      )
      get(
        ':role_id/add_permissions',
        to: 'permissions#add',
        as: :role_add_permissions
      )
      post(
        ':role_id/create_permissions',
        to: 'permissions#create',
        as: :role_create_permissions
      )
      post(
        ':role_id/toggle_permissions',
        to: 'permissions#toggle_permissions',
        as: :role_toggle_permissions
      )
    end

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/delete_avatar', action: :delete_avatar
      get(
        '/reload',
        action: :reload,
        on: :collection
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :scripts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        post '/lang/:locale', to: 'settings#change_locale', as: :change_locale
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end

  scope ":admin_code" do 
    devise_scope :user do
      get '/sign_in', to: 'devise/keppler_sessions#new'
      post '/sign_in', to: 'devise/keppler_sessions#create'
      delete '/sign_out', to: 'devise/keppler_sessions#destroy'
    end
  end

  # Errors routes
  match '/alert/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/alert/404', to: 'errors#not_found', via: :all
  match '/alert/422', to: 'errors#unprocessable', via: :all
  match '/alert/500', to: 'errors#internal_server_error', via: :all

  # Dashboard routes engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'

  # Frontend routes engine
  mount KepplerFrontend::Engine, at: '/', as: 'frontend'

  # Language routes engine
  mount KepplerLanguages::Engine, at: '/', as: 'languages'

  # Capsules routes engine
  mount KepplerCapsules::Engine, at: '/', as: 'capsules'

  # Ckeditor routes engine
  mount Ckeditor::Engine => '/ckeditor' 
end

installer/core/app/models/setting.rb
# frozen_string_literal: true

# Setting Model
class Setting < ApplicationRecord
  include ActivityHistory

  has_one :smtp_setting, dependent: :destroy
  has_one :google_analytics_setting, dependent: :destroy
  has_one :social_account, dependent: :destroy
  has_one :appearance, dependent: :destroy

  accepts_nested_attributes_for(
    :smtp_setting, :google_analytics_setting,
    :social_account, :appearance
  )

  mount_uploader :favicon, AttachmentUploader
  mount_uploader :logo, AttachmentUploader
end

installer/core/app/controllers/admin/settings_controller.rb
# frozen_string_literal: true

module Admin
  # SettingsController
  class SettingsController < AdminController
    include Settings

    before_action :set_setting, only: %i[edit update appearance_default]
    before_action :authorization, except: %i[reload appearance_default]
    after_action :update_settings_yml, only: %i[create update destroy clone]

    def edit
      only_development if params[:config].eql?('appearance')
      @social_medias = social_account_permit_attributes
      @colors = social_account_colors
      @languages = %w[en es]
    end

    def update
      upload_p12(params)

      if @setting.update(setting_params)
        update_ga_status(params)
        appearance_service.get_color(parsed_color)
        redirect_to(
          admin_settings_path(@render), notice: actions_messages(@setting)
        )
      else
        render :edit
      end
    end

    def change_locale
      Appearance.first.update(language: params[:locale])
      I18n.locale = Appearance.first.language
      redirect_back fallback_location: admin_root_path
    end

    def appearance_default
      appearance_service.set_default
      redirect_to(
        admin_settings_path(@render), notice: actions_messages(@setting)
      )
    end

    private

    def appearance_service
      Admin::AppearanceService.new
    end

    def parsed_color
      return if params[:color].nil?

      if params[:color].include?('#') || params[:color].include?('rgb')
        params[:color]
      else
        "##{params[:color]}"
      end
    end

    def update_ga_status(params)
      return unless params[:setting][:google_analytics_setting]
      status = params[:setting][:google_analytics_setting][:ga_status]
      return if status.nil?
      @setting.google_analytics_setting.update(ga_status: status)
    end

    def upload_p12(params)
      return unless params['google_analytics_setting_attributes']
      return unless params['google_analytics_setting_attributes']['p12']
      file = params['google_analytics_setting_attributes']['p12']
      name = file.original_filename
      path = File.join('config', 'gaAuth', name)
      File.open(path, 'wb') { |f| f.write(file.read) }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.first
      @render = params[:config]
    end

    def authorization
      authorize Setting
    end

    # Only allow a trusted parameter 'white list' through.
    def setting_params
      params.require(:setting).permit(
        :name, :description, :email, :phone, :mobile, :logo,
        :favicon, :logo_cache, :favicon_cache,
        smtp_setting_attributes: smpt_setting_permit_attributes,
        google_analytics_setting_attributes: ga_setting_permit_attributes,
        social_account_attributes: social_account_permit_attributes,
        appearance_attributes: apparence_permit_attributes
      )
    end

    def smpt_setting_permit_attributes
      %i[id address port domain_name email password]
    end

    def ga_setting_permit_attributes
      %i[ga_account_id ga_tracking_id ga_status]
    end

    def social_account_permit_attributes
      %i[
        facebook twitter instagram google_plus
        tripadvisor pinterest flickr behance
        dribbble tumblr github linkedin
        soundcloud youtube skype vimeo
      ]
    end

    def social_account_colors
      %w[
        #3b5998 #1da1f2 #e1306c #dd4b39 #00af87 #bd081c #ff0084 #1769ff
        #ff8833 #35465c #333333 #0077b5 #ff8800 #ff0000 #00aff0 #162221
      ]
    end

    def apparence_permit_attributes
      %i[
        id theme_name image_background language admin_code time_zone
        image_background_cache remove_image_background
      ]
    end
  end
end

installer/core/app/controllers/concerns/settings.rb
# frozen_string_literal: true

# DeviseParams
module Settings
  extend ActiveSupport::Concern

  def basic_information_fields
    setting = Setting.first
    [
      Hash['name', setting.name],
      Hash['description', setting.description],
      Hash['email', setting.email],
      Hash['phone', setting.phone],
      Hash['mobile', setting.mobile]
    ]
  end

  def smtp_fields
    smtp = Setting.first.smtp_setting
    [
      Hash['address', smtp.address],
      Hash['port', smtp.port],
      Hash['domain_name', smtp.domain_name],
      Hash['smtp_email', smtp.email]
    ]
  end

  def google_analytics_fields
    google = Setting.first.google_analytics_setting

    [
      Hash['ga_account_id', google.ga_account_id],
      Hash['ga_tracking_id', google.ga_tracking_id],
      Hash['ga_status', google.ga_status]
    ]
  end

  def social_accounts_fields
    setting = Setting.first
    account = setting.social_account

    account_fields(account)
  end

  def appearance_fields
    fields = Setting.first.appearance

    [
      Hash['theme_name', fields.theme_name]
    ]
  end

  def update_settings_yml
    file = File.join("#{Rails.root}/config/settings.yml")

    data = basic_information_fields.push(
      smtp_fields,
      google_analytics_fields,
      social_accounts_fields,
      appearance_fields
    ).flatten.as_json.to_yaml

    File.write(file, data)
    delete_underscores(file)
  end

  def delete_underscores(file)
    yml = File.readlines(file)
    yml.each_with_index do |_line, index|
      if yml[index].include?('-') && yml[index] != "---\n"
        yml[index] = yml[index].tr('-', ' ')
        yml[index] = tracking_id(yml[index]) if yml[index].include?('UA')
      end
    end
    yml = yml.join('')
    File.write(file, yml)
  end

  private

  def tracking_id(string)
    return unless string.include?('UA')
    a = string.split(' ').last(3)
    b = a.first
    c = a.last(2).join('-')
    "  ga_tracking_id: #{b}-#{c}\n"
  end

  def socials
    %i[
      facebook twitter instagram google_plus
      tripadvisor pinterest flickr behance
      dribbble tumblr github linkedin
      soundcloud youtube skype vimeo
    ]
  end

  def account_fields(obj)
    social_accounts = socials.map do |social|
      Hash[social.to_s, obj[social.to_sym]]
    end

    social_accounts
  end
end

installer/core/app/views/admin/settings/fields/_appearance.html.haml
#colors
  = f.simple_fields_for :appearance, html: { multipart: true } do |f|
    .col-md-7.col-lg-6
      .box.slice-box.hidden-xs
        .box-header.with-border
          %h3.box-title= t('keppler.customize.preview')
        / /.box-header
        .box-body.box-body-no-padding
          - if f.object.image_background?
            .appearance-img.devise-new-img{ style: "background-image:url(#{f.object.image_background_url})" }
              = render 'admin/settings/components/preview', f: f
          - else
            .appearance-img{ style: "background-image:url('/assets/admin/profile-menu.jpg')" }
              = render 'admin/settings/components/preview', f: f
    .col-md-5.col-lg-6
      .box.slice-box.p-15
        .box-header.with-border
          %h3.box-title= t('keppler.customize.admin-theme')

        .box-body
          .form-group
            .file-uploader
              .file-container{ style: "background-image: url(#{f.object.image_background_url})", class: ('already-uploaded' if f.object.image_background_url) }
                = f.input :image_background # , multiple: true
                %i.file-icon.icon-picture
                %h5.file-text= t 'keppler.actions.drop_files'
            %p= t 'appearance.main_color'
            %input.form-control.jscolor#colorpicker{ type: 'text', name: 'color', placeholder: 'Color', value: color }
          .pull-right
            = f.button :submit, t('keppler.actions.apply'), class: 'btn btn-primary change-color'
            - if @render.eql?('appearance')
              = link_to appearance_default_admin_settings_path(@render), class: 'btn btn-default', method: :put do
                = t('keppler.actions.appearance_defaut')
:javascript
  $(function() {
      $('#colorpicker').on('change', function(e) {
        color = e.currentTarget.style.backgroundColor
        $('.logo span').css('color', color)
        $('.keppler-background').css('background', color)
        $('.keppler-border-top-color').css('border-top-color', color)
        $('.keppler-border-left-color').css('border-left-color', color)
        $('.sidebar-toggle').css('background', color)
        $('.btn-primary').css('background', color)
        $('.slice-box').css('border-top-color', color)
        $('#span').css('color', color)
        $('.side-img-profile').css('background', color)
        $('.small-profile-img').css('background', color)
        $('.login-logo span').css('color', color)
        $('.login-footer span').css('color', color)
        $('.sidebar-menu > li:hover > a, .sidebar-menu > li.active > a')
          .css({
            'color': color,
            'border-left-color': color
          })
      });
    });

installer/core/app/views/admin/settings/fields/_basic_information.html.haml
.col-lg-6
  .info-box
    %span.info-box-img.info-box-icon#logo{ style: "background-image: url(#{f.object.logo? ? f.object.logo : '/assets/admin/profile-menu.jpg'})" }
    .info-box-content
      %span.info-box-text
        = f.input :logo

  .info-box
    %span.info-box-img.info-box-icon#favicon{ style: "background-image: url(#{f.object.favicon? ? f.object.favicon : '/assets/admin/profile-menu.jpg'})" }
    .info-box-content
      %span.info-box-text
        = f.input :favicon

.col-lg-6
  .box.slice-box.p-15
    .box-header.with-border
      %h3.box-title
        = t('keppler.sidebar-menu.setting-submenu.basic-information')
      .box-tools.pull-right
        %a.btn.btn-box-tool{ 'data-widget' => 'collapse', type: 'button' }
          %i.icon-minus
    .box-body.pure-input
      = f.input :name, input_html: { class: 'form-control' }, required: true, label: t('activerecord.attributes.name'), placeholder: t('activerecord.attributes.name')
      = f.input :description, input_html: { class: 'form-control' }, required: true, label: t('activerecord.attributes.description'), placeholder: t('activerecord.attributes.description')
      = f.input :email, input_html: { class: 'form-control' }, required: false, label: t('activerecord.attributes.email'), placeholder: 'example@domain.com'
      = f.input :phone, input_html: { class: 'form-control' }, required: false, label: t('activerecord.attributes.phone_one'), placeholder: '+584141234567'
      = f.input :mobile, input_html: { class: 'form-control' }, required: false, label: t('activerecord.attributes.phone_two'), placeholder: '+582123536869'
      .pull-right
        = f.button :submit, t('keppler.actions.apply'), class: 'btn-primary'
:javascript
  $(document).ready(function(){
    $("#setting_logo").change(function(){
      $('#logo').css('background-image', "url(" + $(this).val() + ")");
      $('#edit_setting_1').submit();
    });
    $("#setting_favicon").change(function(){
      $('#favicon').css('background-image', "url(" + $(this).val() + ")");
      $('#edit_setting_1').submit();
    })
  });

installer/core/app/views/admin/settings/fields/_configuration.html.haml
#colors
  = f.simple_fields_for :appearance, html: { multipart: true } do |f|
    .box.slice-box.p-15
      .box-header.with-border
        %h3.box-title= t('keppler.customize.login_security_url')

      .box-body
        = f.input :admin_code, label: false, include_blank: false
    .box.slice-box.p-15
      .box-header.with-border
        %h3.box-title= t('keppler.customize.timezone')

      .box-body
        .row
          .col-lg-8
            = f.input :time_zone, label: false, include_blank: false
          .col-lg-4
            .time-zone-test
              %b Time.zone.now =
              = Time.zone.now
    .box.slice-box.p-15
      .box-header.with-border
        %h3.box-title= t('keppler.customize.language')

      .box-body
        = f.input :language, collection: languages.map { |lang| [t("keppler.language.#{lang}"), lang] }, label: false, include_blank: false
        .pull-right
          = f.button :submit, t('keppler.actions.apply'), class: 'btn btn-primary change-color'

installer/core/app/views/admin/settings/fields/_email_setting.html.haml
.col-lg-12
  = f.simple_fields_for :smtp_setting do |f|
    .box.slice-box.p-15
      .box-header.with-border
        %h3.box-title
          = t('keppler.sidebar-menu.setting-submenu.email-setting-smtp')
        .box-tools.pull-right
          %a.btn.btn-box-tool{ 'data-widget' => 'collapse', type: 'button' }
            %i.icon-minus
      .box-body.pure-input
        .form-padding
          = f.input :address
          = f.input :port
          = f.input :domain_name
          = f.input :email
          = f.input :password
        .pull-right
          = f.button :submit, t('keppler.actions.apply'), class: 'btn-primary'

installer/core/app/views/admin/settings/fields/_google_analytics_setting.html.haml
.col-lg-12
  .box.slice-box.p-15
    .box-header.with-border
      %h3.box-title
        = t 'keppler.sidebar-menu.setting-submenu.google-analytics'
    .box-body.pure-input
      .container
        = f.simple_fields_for :google_analytics_setting do |f|
          .row
            .col-lg-6.col-md-6.col-sm-12.col-xs-12
              = f.input :ga_account_id
            .col-lg-6.col-md-6.col-sm-12.col-xs-12
              = f.input :ga_tracking_id
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              %label .p12 File
              = file_field_tag 'google_analytics_setting_attributes[p12]', as: :keppler_file, label: '.p12 file'
            .col-lg-6.col-md-6.col-sm-12.col-xs-12{ style: 'margin-top: 20px' }
              = f.input :ga_status, as: :keppler_boolean
            .col-lg-6.col-md-6.col-sm-12.col-xs-12
              .pull-right
                = f.button :submit, t('keppler.actions.apply'), class: 'btn-primary'

installer/core/app/views/admin/settings/fields/_social_accounts.html.haml
.social-medias-setting.col-lg-12
  .box.slice-box.p-15
    .box-header.with-border
      %h3.box-title
        = t 'keppler.sidebar-menu.setting-submenu.social-accounts'
      .box-tools.pull-right
        %a.btn.btn-box-tool{ 'data-widget' => 'collapse', type: 'button' }
          %i.icon-minus
    .box-body.pure-input
      .form-padding
        = f.simple_fields_for :social_account do |f|
          .row
            - @social_medias.each_with_index do |social, color|
              .col-lg-6.col-md-6.col-sm-12.col-xs-12
                = f.input social

                -# To show a social media icon before input
                :javascript
                  var input = $("#setting_social_account_attributes_#{social}")
                  input.before(
                    `<i style="color:#9e9e9e" class="social-icons prefix fab fa-#{social.to_s.split('_').join('-')}"></i>`
                    )
                  input.focus(function(){
                    $('.fa-#{social.to_s.split('_').join('-')}').css('color', "#{@colors[color]}")
                  })
                  input.blur(function(){
                    $('.fa-#{social.to_s.split('_').join('-')}').css('color', "#9e9e9e")
                  });

                -# To activate colors in social media inputs
                :sass
                  .setting_social_account_#{social}
                    i.active
                      color: #{@colors[color]} !important
                    input:focus:not([readonly])
                      border: 1px solid #{@colors[color]} !important
                      // box-shadow: 0 1px 0 0 #{@colors[color]} !important
                    .control-label.active
                      color: #{@colors[color]} !important
          .row
            .col-lg-12
              .pull-right
                = f.button :submit, t('keppler.actions.apply'), class: 'btn-primary'