installer/core/config/routes.rb
Rails.application.routes.draw do
  localized do
    get '/index', to: 'app/front#index', as: :app_index
  end

  # root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  post '/filter', to: 'admin/users#filter_by_role', as: :filter_by_role

  namespace :admin do
    root to: 'admin#root'

    namespace :rockets do
      get '/', action: :rockets
      post 'create/:rocket', action: :create, as: :create
      post 'install', action: :install
      post 'build/:rocket', action: :build, as: :build
      delete 'uninstall/:rocket', action: :uninstall, as: :uninstall
    end

    get '/seo/sitemap', to: 'seos#sitemap'
    get '/seo/robots', to: 'seos#robots'
    post '/seo/editor/save', to: 'seos#editor_save'

    resources :seos do
      post '/sort', action: :sort, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :roles do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get '/download', action: 'download', as: :download
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      # post '/show_description/:module/:action_name', action: 'show_description', as: :show_description
      # get(
      #   '/add_permissions',
      #   action: 'add_permissions',
      #   as: :add_permissions
      # )
      # post(
      #   '/create_permissions',
      #   action: 'create_permissions',
      #   as: :create_permissions
      # )
    end

    scope :roles do
      post(
        ':role_id/show_description/:module/:action_name',
        to: 'permissions#show',
        as: :role_show_description
      )
      get(
        ':role_id/add_permissions',
        to: 'permissions#add',
        as: :role_add_permissions
      )
      post(
        ':role_id/create_permissions',
        to: 'permissions#create',
        as: :role_create_permissions
      )
      post(
        ':role_id/toggle_permissions',
        to: 'permissions#toggle_permissions',
        as: :role_toggle_permissions
      )
    end

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/delete_avatar', action: :delete_avatar
      get(
        '/reload',
        action: :reload,
        on: :collection
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :scripts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        post '/lang/:locale', to: 'settings#change_locale', as: :change_locale
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end

  scope ":admin_code" do 
    devise_scope :user do
      get '/sign_in', to: 'devise/keppler_sessions#new'
      post '/sign_in', to: 'devise/keppler_sessions#create'
      delete '/sign_out', to: 'devise/keppler_sessions#destroy'
    end
  end

  # Errors routes
  match '/alert/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/alert/404', to: 'errors#not_found', via: :all
  match '/alert/422', to: 'errors#unprocessable', via: :all
  match '/alert/500', to: 'errors#internal_server_error', via: :all

  # Dashboard routes engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'

  # Frontend routes engine
  mount KepplerFrontend::Engine, at: '/', as: 'frontend'

  # Language routes engine
  mount KepplerLanguages::Engine, at: '/', as: 'languages'

  # Capsules routes engine
  mount KepplerCapsules::Engine, at: '/', as: 'capsules'

  # Ckeditor routes engine
  mount Ckeditor::Engine => '/ckeditor' 
end

installer/core/app/models/rocket.rb
# frozen_string_literal: true

# Rocket Model
class Rocket
  attr_reader :name

  def initialize(name = '')
    @name = name
  end

  # Rockets list
  def self.names_list
    Dir["#{Rails.root}/rockets/*"].map do |dir|
      rocket_name = dir.split('/').last
      dir_size = 0
      Dir.glob("#{dir}/**/**").map do |file|
        dir_size += File.size(file)
      end
      "#{rocket_name} (#{filesize(dir_size)})"
    end
  end

  # Rockets needed for the core
  def self.core_depending
    %w[keppler_frontend keppler_ga_dashboard]
  end

  # Create rocket
  def self.new_rocket(rocket)
    system "rails g new_rocket #{rocket}"
  end

  # Catching rocket file and saving in public/rockets
  def self.save_and_rename(rocket_file)
    dir = Rails.root.join('public', 'rockets')
    Dir.mkdir(dir) unless Dir.exist?(dir)
    tmp = rocket_file.tempfile
    destiny_file = File.join("#{Rails.root}/public/rockets")
    FileUtils.move tmp.path, destiny_file
    File.rename(
      "#{destiny_file}/#{tmp.path.split('/')[-1]}",
      "#{destiny_file}/#{rocket_file.original_filename}"
    )
  end

  # Unzipping into rockets folder
  def self.unzip(rocket_file, rocket_name)
    require 'zip'
    rocket_zip = "#{Rails.root}/public/rockets/#{rocket_file.original_filename}"
    Zip::File.open(rocket_zip) do |zip_file|
      dir = Rails.root.join('rockets', rocket_name)
      Dir.mkdir(dir) unless Dir.exist?(dir)
      uncompress_pkg(zip_file, rocket_name)
    end
  end

  # Installing rocket
  def self.install(rocket_name)
    system "rails g install_rocket #{rocket_name}"
  end

  # Uninstall rocket
  def self.uninstall(rocket_name)
    system "rails g uninstall_rocket #{rocket_name}"
  end

  # Build rocket
  def self.build(rocket)
    rocket_dir = "#{Rails.root}/rockets/#{rocket}"
    Dir.mkdir("#{rocket_dir}/pkg") unless Dir.exist?("#{rocket_dir}/pkg")
    compress_pkg(rocket_dir)
    public_rockets = "#{Rails.root}/public/rockets"
    Dir.mkdir(public_rockets) unless Dir.exist?(public_rockets)
    system "cp #{rocket_dir}/pkg/#{rocket}.rocket #{public_rockets}"
  end

  # private

  def self.compress_pkg(rocket_dir)
    archive = "#{rocket_dir}/pkg/#{File.basename(rocket_dir)}.rocket"
    require 'zip'
    return if File.exist? archive
    Zip::File.open(archive, 'w') do |zipfile|
      Dir["#{rocket_dir}/**/**"].reject { |f| f.eql? archive }.each do |file|
        zipfile.add(file.sub(rocket_dir + '/', ''), file)
      end
    end
  end

  def self.uncompress_pkg(zip_file, rocket_name)
    zip_file.each do |entry|
      unless File.exist?("#{Rails.root}/rockets/#{rocket_name}/#{entry.name}")
        puts "*** Extracting #{entry.name} ***"
        entry.extract("#{Rails.root}/rockets/#{rocket_name}/#{entry.name}")
      end
    end
  end

  def self.filesize(size)
    units = %w[B KB MB GB TB Pb EB]
    return '0.0 B' if size.zero?
    exp = (Math.log(size) / Math.log(1024)).to_i
    exp = 6 if exp > 6
    [(size.to_f / 1024**exp).round(2), units[exp]].join(' ')
  end

  def self.parse_name(rocket_name)
    rocket_name
      .remove(':', ';', '\'', '"')
      .downcase
      .parameterize
      .dasherize
      .remove('keppler-')
      .underscore
  end
end

installer/core/app/controllers/admin/rockets_controller.rb
# frozen_string_literal: true

module Admin
  # RocketsController
  class RocketsController < AdminController
    skip_before_action :verify_authenticity_token
    before_action :rocket_params, except: %i[rockets install]
    before_action :rocket_file_params, only: %i[install]
    before_action :authorization

    def rockets
      @rockets = Rocket.names_list
    end

    def create
      rocket = Rocket.parse_name(@rocket)
      if (Dir.exist? "#{Rails.root}/rockets/keppler_#{rocket}") || rocket.blank?
        @error = true
        puts "\n\n!!!!! Rocket keppler_#{rocket} is already created !!!!!\n\n"
      else
        Rocket.new_rocket(@rocket_undescore_name)
      end
      redirect_to_rockets_list(@error ? 'error' : @rocket)
    end

    def install
      return unless @rocket && @rocket_file_ext.eql?('rocket')
      install_process(@rocket, @rocket_file_name)
      redirect_to_rockets_list(@rocket)
    end

    def uninstall
      Rocket.uninstall(@rocket)
      redirect_to_rockets_list(@rocket)
    end

    def build
      Rocket.build(@rocket)
      redirect_to_rockets_list(@rocket)
    end

    private

    # def uninstall_authorize
    #   @rocket = params[:rocket]
    #   rocket_policy = RocketPolicy.new(current_user, @rocket)
    #   rocket_policy.uninstall?
    # end

    def authorization
      authorize Rocket.new(@rocket)
    end

    def rocket_params
      @rocket = params[:rocket]
      @rocket_undescore_name = @rocket.parameterize.underscore
      @rocket_class_name = @rocket_undescore_name.classify
    end

    def rocket_file_params
      @rocket = params[:rocket]
      @rocket_file_name = @rocket.original_filename.split('.').first
      @rocket_file_ext = @rocket.original_filename.split('.').last
    end

    def install_process(rocket_param, rocket_file_name)
      Rocket.save_and_rename(rocket_param)
      Rocket.unzip(rocket_param, rocket_file_name)
      Rocket.install(rocket_file_name)
    end

    def redirect_to_rockets_list(rocket)
      message_action
      state = rocket.eql?('error') ? 'error' : 'success'
      flash[state.to_sym] =
        t(
          "keppler.rockets.#{state.eql?('error') ? 'duplicated' : 'success'}",
          rocket: rocket_name(@rocket),
          action: t("keppler.rockets.#{@action}")
        )
      redirect_to admin_rockets_path
    end

    def rocket_name(rocket)
      name =
        if rocket.try(:original_filename).nil?
          Rocket.parse_name(rocket)
        else
          Rocket.parse_name(rocket.original_filename.split('.').first)
        end
      "keppler_#{name}".camelize
    end

    def message_action
      @action =
        case action_name
        when 'build'
          'built'
        when 'create'
          "#{action_name}d"
        else
          "#{action_name}ed"
        end
    end
  end
end

installer/core/app/helpers/rockets_helper.rb
# frozen_string_literal: true

# RocketsHelper
module RocketsHelper
  def rocket_is_built?(rocket)
    File.file?("#{Rails.root}/public/rockets/#{rocket}.rocket")
  end

  def can_uninstall?(rocket_name)
    RocketPolicy.new(current_user, rocket_name).uninstall?
  end
end

installer/core/app/views/admin/rockets/_create_rocket.haml
:javascript
  $('.create-rocket').click(function () {
    swal({
      input: 'text',
      title: "#{t('keppler.rockets.choose_a_name')}",
      text: "#{t('keppler.rockets.rocket_name')}",
      confirmButtonText: "#{t('keppler.rockets.create_rocket')}",
      cancelButtonText: "#{t('keppler.rockets.cancel')}",
      showCancelButton: true,
    }).then((result) => {
      if (parseRocketName(result.value) && parseRocketName(result.value) != '') {
        var rocket_name = parseRocketName(result.value);
        swal({
          title: "#{t('keppler.rockets.you_sure')}",
          html: `#{t('keppler.rockets.will_be_named')}:<pre><code>keppler_${parseRocketName(result.value)}</code></pre>`,
          confirmButtonText: "#{t('keppler.rockets.great')}",
          showCancelButton: true,
        }).then((result) => {
          if (result.value) {
            swal({
              title: "#{t('keppler.rockets.great')}",
              html: "#{t('keppler.rockets.wait_generator')}",
              timer: 3000,
              onOpen: () => {
                swal.showLoading()
              },
            }).then((result) => {
              $('.spinner').fadeIn()
              $('.create_rocket_form')
                .attr('action', `/admin/rockets/create/${rocket_name}`)
                .submit()
              // if (result.dismiss === swal.DismissReason.timer) {
              // }
            })
          }
        })
      } else {
        swal({
          title: 'Oops!',
          html: "#{t('keppler.rockets.unpermitted_name')}",
          timer: 3000
        })
      }
    })
  })

  function parseRocketName(rocket_name) {
    var rn = rocket_name
      .toLowerCase()
      .split('keppler').join('')

    var valid_chars = [];
    for (var i = 0; i < rn.split('').length; i++){
      var char = rn.split('')[i]
      if ([' ', '_'].includes(char)) valid_chars.push('_')
      else if (/[a-zA-Z]/.test(char)) valid_chars.push(char);
    }
    rn = valid_chars.join('')
    while (rn[0]=='_') rn = rn.substring(1, rn.length);
    return rn
  }

installer/core/app/views/admin/rockets/_install_rocket.haml
:coffee

  showSpinner = ->
    $ '.spinner'
      .css 'display', 'block'

  #Only for rockets
  installRocket = (evt) ->
    evt.preventDefault()
    rocket_file = $('.file-uploader input:file').val()
    can_install = true
    if rocket_file isnt ''
      if rocket_file.includes('.rocket')
        $('.rocket-name').each ->
          if rocket_file.includes $(this).text()
            swal "#{I18n.t('keppler.rockets.already_installed')}"
            can_install = false
        if can_install
          showSpinner()
          $ '.upload_rocket_form'
            .submit()
      else
        swal "#{I18n.t('keppler.rockets.isnt_a_rocket')}"
    else
      swal "#{I18n.t('keppler.rockets.first_upload')}"

  $('#installRocket').on 'click', installRocket

installer/core/app/views/admin/rockets/rockets.haml
.row.customize-index#index-container
  .col-md-6.col-lg-6
    .box.slice-box
      .box-header.with-border
        %h3.box-title= t('keppler.rockets.upload')
      .box-body.box-body-no-padding
        = simple_form_for 'upload_rocket_form', url: admin_rockets_install_path, html: { multipart: true } do
          .file-uploader
            .file-container
              = file_field_tag :rocket # , multiple: true
              %i.file-icon.bx.bx-rocket
              %h5.file-text= t 'keppler.rockets.drop'
            %a.spinnerTrigger#installRocket
              %i.bx.bx-rocket
              = t 'keppler.rockets.install'

  .col-md-6.col-lg-6
    .box.slice-box
      .box-header.with-border
        %h3.box-title= t('keppler.rockets.list')
        .pull-right
          = simple_form_for 'create_rocket_form', url: admin_rockets_create_path('rocket') do
            %a.create-rocket
              %i.icon-plus
              = t 'keppler.rockets.create_a_rocket'
      .box-body.no-padding
        %table.table
          %tbody
            - if @rockets.blank?
              %tr
                %td{ colspan: 4 }
                  %center
                    = t 'keppler.rockets.empty'
            - else
              - @rockets.each do |rocket|
                %tr
                  %td
                    %i.bx.bx-rocket
                    %span.rocket-name= rocket.split('keppler_').last.humanize
                    .pull-right
                      - rocket_name = rocket.split(' ')[0..-3].join(' ')
                      - if rocket_is_built?(rocket_name)
                        = link_to admin_rockets_build_path(rocket_name), method: :post, 'data-toggle': 'tooltip', 'data-original-title': t('keppler.rockets.update') do
                          %i.icon-wrench
                        = link_to "/rockets/#{rocket_name}.rocket", dowload: "#{rocket_name}.rocket", 'data-toggle': 'tooltip', 'data-original-title': t('keppler.rockets.download') do
                          %i.icon-cloud-download
                      - else
                        = link_to admin_rockets_build_path(rocket_name), method: :post, 'data-toggle': 'tooltip', 'data-original-title': t('keppler.rockets.build') do
                          %i.icon-wrench
                      - if can?(Rocket.new(rocket_name)).uninstall?
                        = link_to admin_rockets_uninstall_path(rocket_name), class: 'uninstallRocket', 'data-toggle': 'tooltip', 'data-original-title': t('keppler.rockets.uninstall'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                          %i.icon-trash.text-red
                      - else
                        = link_to '#', class: 'uninstallRocket', 'data-toggle': 'tooltip', style: 'color: #c0c0c0 !important;' do
                          %i.icon-trash
= render 'install_rocket'
= render 'create_rocket'