installer/core/config/routes.rb
Rails.application.routes.draw do
  localized do
    get '/index', to: 'app/front#index', as: :app_index
  end

  # root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  post '/filter', to: 'admin/users#filter_by_role', as: :filter_by_role

  namespace :admin do
    root to: 'admin#root'

    namespace :rockets do
      get '/', action: :rockets
      post 'create/:rocket', action: :create, as: :create
      post 'install', action: :install
      post 'build/:rocket', action: :build, as: :build
      delete 'uninstall/:rocket', action: :uninstall, as: :uninstall
    end

    get '/seo/sitemap', to: 'seos#sitemap'
    get '/seo/robots', to: 'seos#robots'
    post '/seo/editor/save', to: 'seos#editor_save'

    resources :seos do
      post '/sort', action: :sort, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :roles do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get '/download', action: 'download', as: :download
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      # post '/show_description/:module/:action_name', action: 'show_description', as: :show_description
      # get(
      #   '/add_permissions',
      #   action: 'add_permissions',
      #   as: :add_permissions
      # )
      # post(
      #   '/create_permissions',
      #   action: 'create_permissions',
      #   as: :create_permissions
      # )
    end

    scope :roles do
      post(
        ':role_id/show_description/:module/:action_name',
        to: 'permissions#show',
        as: :role_show_description
      )
      get(
        ':role_id/add_permissions',
        to: 'permissions#add',
        as: :role_add_permissions
      )
      post(
        ':role_id/create_permissions',
        to: 'permissions#create',
        as: :role_create_permissions
      )
      post(
        ':role_id/toggle_permissions',
        to: 'permissions#toggle_permissions',
        as: :role_toggle_permissions
      )
    end

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/delete_avatar', action: :delete_avatar
      get(
        '/reload',
        action: :reload,
        on: :collection
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :scripts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        post '/lang/:locale', to: 'settings#change_locale', as: :change_locale
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end

  scope ":admin_code" do 
    devise_scope :user do
      get '/sign_in', to: 'devise/keppler_sessions#new'
      post '/sign_in', to: 'devise/keppler_sessions#create'
      delete '/sign_out', to: 'devise/keppler_sessions#destroy'
    end
  end

  # Errors routes
  match '/alert/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/alert/404', to: 'errors#not_found', via: :all
  match '/alert/422', to: 'errors#unprocessable', via: :all
  match '/alert/500', to: 'errors#internal_server_error', via: :all

  # Dashboard routes engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'

  # Frontend routes engine
  mount KepplerFrontend::Engine, at: '/', as: 'frontend'

  # Language routes engine
  mount KepplerLanguages::Engine, at: '/', as: 'languages'

  # Capsules routes engine
  mount KepplerCapsules::Engine, at: '/', as: 'capsules'

  # Ckeditor routes engine
  mount Ckeditor::Engine => '/ckeditor' 
end

installer/core/app/models/meta_tag.rb
# frozen_string_literal: true

# MetaTag Model
class MetaTag < ApplicationRecord
  include ActivityHistory
  include CloneRecord
  include Uploadable
  include Downloadable
  include Sortable
  acts_as_list
  before_save :split_url
  validates_uniqueness_of :url

  validates_presence_of :title, :meta_tags, :url

  def self.get_by_url(url)
    url = url.split('//').last.split('www.').last
    find_by_url(url)
  end

  def self.title(post_param, product_param, setting)
    post = post_param&.title
    product = product_param&.title || product_param&.name
    post || product || setting.name
  end

  def self.description(post_param, product_param, setting)
    unless post_param&.body.blank?
      body = post_param.body
      post = sanitize(body, tags: []).truncate(300)
    end
    product = product_param&.description || product_param&.body
    post || product || setting.description
  end

  def self.image(request, post_param, product_param, setting_param)
    post = post_param&.image
    product = product_param&.image || product_param&.photo
    setting = setting_param&.logo unless setting_param&.logo.blank?
    image = '/assets/admin/slice.png'
    url = request.protocol + request.host_with_port
    url + (post || product || setting || image).to_s
  end

  def self.search_field
    :title_or_description_or_url_cont_any
  end

  private

  def split_url
    self.url = url.split('//').last.split('www.').last
  end
end

installer/core/app/controllers/admin/meta_tags_controller.rb
# frozen_string_literal: true

module Admin
  # MetaTagController
  class MetaTagsController < AdminController
    before_action :set_meta_tag, only: %i[show edit update destroy]
    before_action :show_history, only: %i[index]
    before_action :authorization, except: %i[reload]
    include ObjectQuery

    # GET /meta_tags
    def index
      @q = MetaTag.ransack(params[:q])
      @meta_tags = @q.result(distinct: true)
      @objects = @meta_tags.page(@current_page).order(position: :desc)
      @total = @meta_tags.size
      redirect_to_index(@objects)
      respond_to_formats(@meta_tags)
    end

    # GET /meta_tags/1
    def show; end

    # GET /meta_tags/new
    def new
      @meta_tag = MetaTag.new
    end

    # GET /meta_tags/1/edit
    def edit; end

    # POST /meta_tags
    def create
      @meta_tag = MetaTag.new(meta_tag_params)
      if @meta_tag.save
        redirect(@meta_tag, params)
      else
        render :new
      end
    end

    # PATCH/PUT /meta_tags/1
    def update
      if @meta_tag.update(meta_tag_params)
        redirect(@meta_tag, params)
      else
        render :edit
      end
    end

    def clone
      @meta_tag = MetaTag.clone_record params[:meta_tag_id]

      if @meta_tag.save
        redirect_to admin_meta_tags_path
      else
        render :new
      end
    end

    # DELETE /meta_tags/1
    def destroy
      @meta_tag.destroy
      redirect_to admin_meta_tags_path, notice: actions_messages(@meta_tag)
    end

    def destroy_multiple
      MetaTag.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_meta_tags_path(page: @current_page, search: @query),
        notice: actions_messages(@meta_tag)
      )
    end

    def upload
      MetaTag.upload(params[:file])
      redirect_to(
        admin_meta_tags_path(page: @current_page, search: @query),
        notice: actions_messages(@meta_tag)
      )
    end

    def download
      @meta_tags = MetaTag.all
      respond_to_formats(@meta_tags)
    end

    def reload
      @objects = MetaTag.order(:position)
    end

    def sort
      MetaTag.sorter(params[:row])
      render :index
    end

    private

    def authorization
      authorize MetaTag
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_meta_tag
      @meta_tag = MetaTag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def meta_tag_params
      params.require(:meta_tag).permit(:title, :description,
                                       :meta_tags, :url, :position)
    end

    def show_history
      get_history(MetaTag)
    end
  end
end

installer/core/app/views/admin/meta_tags/_description.html.haml
%aside.control-sidebar.control-sidebar-light
  .tab-content
    %p.control-sidebar-heading
      = activities.empty? ? t('keppler.messages.no_events') : t('keppler.titles.history')
    %ul.timeline
      - @activities.each do |activity|
        - if activity.trackable_type.eql? 'Session'
          %li
            = render partial: "public_activity/session/#{activity.key.split('.').second}", locals: { activity: activity, method: 'title' }
        - else
          %li
            = render partial: "public_activity/layout/#{activity.key.split('.').second}", locals: { activity: activity, method: 'title' }
.control-sidebar-bg

installer/core/app/views/admin/meta_tags/_form.html.haml
= simple_form_for [:admin, @meta_tag] do |f|
  .container
    .row
      .col-lg-2
        = link_to admin_meta_tags_path, 'data-position' => 'bottom', 'data-tooltip' => t('keppler.actions.back') do
          .arrow-back.btn.btn-default
            %i.icon-arrow-left
            = t('keppler.actions.back')
    .row
      .col-lg-12
        .box.slice-box.p-15
          .box-header.with-border
            %h3.box-title= controller_name.humanize
          .box-body
            %table.table.table-bordered
              %tbody
                .form-padding
                  .row
                    .col-lg-6
                      = f.input :title, required: true, autofocus: true

                    .col-lg-6
                      = f.input :url, required: true
                  .row
                    .col-lg-12
                      = f.input :meta_tags, required: true
                  .row
                    .col-lg-12
                      = f.input :description

                  .row
                    .col-lg-12
                      .pull-right
                        = f.button :submit, t('keppler.actions.save'), name: '_save', class: 'btn-primary'
                        = f.button :submit, t('keppler.actions.save_and_add_another'), name: '_add_other'

installer/core/app/views/admin/meta_tags/_listing.html.haml
- objects.each do |meta_tag|
  %tr{ id: "row-#{meta_tag.id}" }
    %td.item-check
      - if can?(MetaTag).destroy_multiple?
        .checkbox
          %label{ for: "checkbox-#{meta_tag.id}" }
            %input{ type: 'checkbox', id: "checkbox-#{meta_tag.id}", 'checklist-model' => 'check', 'checklist-value' => meta_tag.id, 'ng-click' => "selectByCheck(#{objects.size})", '@click' => "listDelete(#{meta_tag.id})" }
            %span.cr
              %i.cr-icon.glyphicon.glyphicon-ok
    %td.hidden-xs.hidden-sm
    %td.hidden-xs.hidden-sm
      = link_to admin_meta_tag_path(meta_tag), title: t('keppler.actions.show') do
        %span= meta_tag.title
    %td.text-overflow{ style: 'max-width: 200px' }
      = link_to admin_meta_tag_path(meta_tag), title: t('keppler.actions.show') do
        %span= meta_tag.url
    %td.dropdown{ style: 'padding-right: 30px;' }
      %a.dropdown-toggle.pull-right{ id: "menu-#{meta_tag.id}", 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown' }
        %i.icon-options-vertical
      %ul.actions.dropdown-menu{ 'aria-labelledby' => "menu-#{meta_tag.id}" }
        - if can?(MetaTag).show?
          %li
            = link_to admin_meta_tag_path(meta_tag), title: t('keppler.actions.show') do
              %i.icon-eye
              = t('keppler.actions.show')
        - if can?(MetaTag).update?
          %li
            = link_to edit_admin_meta_tag_path(meta_tag), title: t('keppler.actions.edit') do
              %i.icon-pencil
              = t('keppler.actions.edit')
        - if can?(MetaTag).clone?
          %li
            = link_to admin_meta_tag_clone_path(meta_tag), title: t('keppler.actions.clone') do
              %i.icon-docs
              = t('keppler.actions.clone')
        - if can?(MetaTag).destroy?
          %li
            = link_to admin_meta_tag_path(meta_tag), title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
              %i.icon-trash
              = t('keppler.actions.delete')

installer/core/app/views/admin/meta_tags/edit.html.haml
= title(t('keppler.titles.edit', model: 'Meta tags'))
= render 'form'

installer/core/app/views/admin/meta_tags/index.html.haml
#index-container{ controller: 'meta_tags' }
  .container
    .row
      .listing.col-lg-12.col-xs-12
        %section.content-header.index-header
          %h1
            = t("keppler.modules.#{controller_path.underscore}")
          = entries(@total, @objects)
        %section.content-actions
          .toolbar
            .toolbar-item
              = link_to reload_admin_meta_tags_path, class: 'tool-btn', remote: true do
                %i.icon-reload
            - if can?(MetaTag).download?
              %li.toolbar-item.dropdown
                %a.dropdown-toggle{ 'data-toggle' => 'dropdown', href: '#', title: t('keppler.actions.download_records') }
                  %i.icon-cloud-download
                %ul.dropdown-menu
                  %li= link_to 'Descargar CSV', admin_meta_tags_path(format: :csv), class: 'tool-btn'
                  %li= link_to 'Descargar XLS', admin_meta_tags_path(format: :xls), class: 'tool-btn'
            - if can?(MetaTag).upload?
              .toolbar-item
                = link_to '#', class: 'tool-btn', title: t('keppler.actions.upload_records'), id: 'upload' do
                  %i.icon-cloud-upload
            .toolbar-item
              %a.tool-btn{ 'data-confirm' => t('keppler.messages.data_confirm'), 'data-method' => 'delete', 'v-bind:href' => 'link', rel: 'nofollow', ':class' => '{disabled: !checks}' }
                %i.icon-trash
          .hide
            = form_tag admin_meta_tag_upload_path(@objects), id: 'upload-form', multipart: true, method: :post do
              = file_field_tag :file, id: 'upload-file'
          - if can?(MetaTag).create?
            .add
              = link_to new_admin_meta_tag_path, class: 'btn-add' do
                +
                = t('keppler.actions.add')

        .box.slice-box
          .box-body.no-padding
            %table.table
              %thead
                - if @objects.size.zero?
                  %tr
                    %th.not-records.center
                      %h6= t('keppler.messages.not_found_records', model: t('keppler.models.pluralize.meta_tags'))
                - else
                  %tr
                    %th
                      - if can?(MetaTag).destroy_multiple?
                        .item-check
                          .checkbox
                            %label{ for: 'checkbox-all' }
                              %input{ type: 'checkbox', id: 'checkbox-all', '@click' => 'selectAll()' }
                              %span.cr
                                %i.cr-icon.glyphicon.glyphicon-ok
                    %th
                    %th
                      = sort_link(@q, :title) do
                        = t('activerecord.attributes.title')
                    %th
                      = sort_link(@q, :url) do
                        = t('activerecord.attributes.url')
                    %th
              %tbody.objects-container{ 'data-update-url' => sort_admin_meta_tags_path.to_s }
                = render 'admin/layouts/listing_preloader'
                = render 'listing', objects: @objects, query: @query
        %center.paginator-module
          = paginate @objects, window: 1
  .listing-show.col.l3.m12.hidden-xs.hidden-sm.hide-on-med-and-down
    = render 'description', activities: @activities

installer/core/app/views/admin/meta_tags/new.html.haml
= title(t('keppler.titles.new', model: 'Meta tags'))
= render 'form'

installer/core/app/views/admin/meta_tags/reload.js.haml
$('.objects-container').html("#{j render 'listing', objects: @objects}");
$('.objects-container').css('opacity', '0');
$('.spinner2').css('display', 'block');
var request = $.ajax({url: '/admin/meta_tags', method: 'get', dataType: 'html'});
request.done(function(msg){$('.spinner2').css('display', 'none');$('.objects-container').css('opacity', '1');});

installer/core/app/views/admin/meta_tags/show.html.haml
.container
  .row
    .col-lg-2
      = link_to admin_meta_tags_path, 'data-position' => 'bottom', 'data-tooltip' => t('keppler.actions.back') do
        .arrow-back.btn.btn-default
          %i.icon-arrow-left
          = t('keppler.actions.back')
          .clearfix
  .show-section
    .row
      .col-lg-12
        .box.slice-box.p-15
          .box-header.with-border
            %h3.box-title= t 'keppler.sidebar-menu.seo-submenu.title-metas'
            .box-tools.pull-right
              - if can?(MetaTag).update?
                = link_to edit_admin_meta_tag_path(@meta_tag), class: 'btn btn-box-tool', title: t('keppler.actions.edit') do
                  %i.icon-pencil
              - if can?(MetaTag).destroy?
                = link_to admin_meta_tag_path(@meta_tag), class: 'btn btn-box-tool', title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                  %i.icon-trash
          .box-body.box-body-no-padding
            %table.table
              %tbody
                - @meta_tag.as_json(only: %w[id title description meta_tags url created_at]).each do |attribute, value|
                  %tr.list-row
                    %th.display-label= t("activerecord.attributes.#{attribute}")
                    %td.display-value.fs-body-1.tc-black-2= value